"""Subclass of MyFrame, which is generated by wxFormBuilder."""

import wx
import mwhois

# Implementing MyFrame
class MainGUI( mwhois.MyFrame ):
	
	def __init__( self, parent ):
		mwhois.MyFrame.__init__( self, parent )
	
	# Handlers for MyFrame events.
	def set_preveiw_results( self, event ):
		# TODO: Implement set_preveiw_results
		print('called set_preveiw_results()')		
		pass
	
	def do_whois_search( self, event ):
		# TODO: Implement do_whois_search
		print('called do_whois_search()')
		pass
	
	def do_print_results( self, event ):
		# TODO: Implement do_print_results
		print('called do_print_results()')
		pass
	
	def do_save_results( self, event ):
		# TODO: Implement do_save_results
		print('called do_save_results()')
		pass
	
	def close_app( self, event ):
		# TODO: Implement close_app
		print('called close_app()')
		wx.Window.Close(self, force=False)
		pass
	
	def open_file_select( self, event ):
		# TODO: Implement open_file_select
		print('called open_file_select()')
		pass
	
	def do_multi_search( self, event ):
		# TODO: Implement do_multi_search
		print('called do_multi_search()')
		pass
	
	def do_get_tld(self, event):
		print('called do_get_tld() ')
		pass

if __name__ == "__main__":
	app = wx.App(False)
	frame = MainGUI(None)
	frame.Show(True)
	app.MainLoop()
