#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Mon Jul 26 20:33:51 2010

import wx

# begin wxGlade: extracode
# end wxGlade


class MyApp(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyApp.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.notebook_1_pane = wx.Panel(self.notebook_1, -1)
        self.sizer_5_staticbox = wx.StaticBox(self.notebook_1_pane_2, -1, "mwhois")
        self.sizer_1_staticbox = wx.StaticBox(self.notebook_1_pane, -1, "mwhois")
        
        # Menu Bar
        self.mwhois_top_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.close = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "Close", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.close)
        self.mwhois_top_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        self.about = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "About", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.about)
        self.mwhois_top_menubar.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.mwhois_top_menubar)
        # Menu Bar end
        self.single_lbl = wx.StaticText(self.notebook_1_pane, -1, "Enter domain Name:", style=wx.ALIGN_CENTRE)
        self.single_txt = wx.TextCtrl(self.notebook_1_pane, -1, "", style=wx.TE_PROCESS_ENTER)
        self.single_button = wx.Button(self.notebook_1_pane, -1, "Single Search")
        self.single_txt_area = wx.TextCtrl(self.notebook_1_pane, -1, "", style=wx.TE_MULTILINE)
        self.single_quit_btn = wx.Button(self.notebook_1_pane, -1, "Quit")
        self.input_lbl = wx.StaticText(self.notebook_1_pane_2, -1, "Input Wordlist:")
        self.input_txt = wx.TextCtrl(self.notebook_1_pane_2, -1, "", style=wx.TE_PROCESS_ENTER)
        self.input_btn = wx.Button(self.notebook_1_pane_2, -1, "Open")
        self.save_lbl = wx.StaticText(self.notebook_1_pane_2, -1, "Output Domainlist:")
        self.save_txt = wx.TextCtrl(self.notebook_1_pane_2, -1, "")
        self.save_btn = wx.Button(self.notebook_1_pane_2, -1, "Save")
        self.adv_txt = wx.StaticText(self.notebook_1_pane_2, -1, "Advanced Search:")
        self.adv_chkbox = wx.CheckBox(self.notebook_1_pane_2, -1, "")
        self.adv_txt_area = wx.TextCtrl(self.notebook_1_pane_2, -1, "", style=wx.TE_MULTILINE)
        self.begin_btn = wx.Button(self.notebook_1_pane_2, -1, "Begin")
        self.adv_quit_btn = wx.Button(self.notebook_1_pane_2, -1, "Quit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.close_app, self.close)
        self.Bind(wx.EVT_MENU, self.about_diag, self.about)
        self.Bind(wx.EVT_BUTTON, self.single_search, self.single_button)
        self.Bind(wx.EVT_BUTTON, self.close_app, self.single_quit_btn)
        self.Bind(wx.EVT_BUTTON, self.open_file, self.input_btn)
        self.Bind(wx.EVT_BUTTON, self.save_file, self.save_btn)
        self.Bind(wx.EVT_CHECKBOX, self.adv_search, self.adv_chkbox)
        self.Bind(wx.EVT_BUTTON, self.perform_multi, self.begin_btn)
        self.Bind(wx.EVT_BUTTON, self.close_app, self.adv_quit_btn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyApp.__set_properties
        self.SetTitle("mwhois widget")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("D:\\My Documents\\development\\xwh0i5\\media\\icon.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((550, 642))
        self.single_lbl.SetMinSize((130, 14))
        self.single_lbl.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.single_txt.SetMinSize((178, 21))
        self.single_txt.SetFocus()
        self.single_button.SetMinSize((99, 23))
        self.single_txt_area.SetMinSize((524, 483))
        self.input_lbl.SetMinSize((120, 13))
        self.input_lbl.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.input_txt.SetMinSize((200, 21))
        self.save_lbl.SetMinSize((120, 13))
        self.save_lbl.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.save_txt.SetMinSize((200, 21))
        self.adv_txt.SetMinSize((120, 20))
        self.adv_txt.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.adv_chkbox.SetMinSize((13, 13))
        self.adv_txt_area.SetMinSize((524,440))
        self.adv_txt_area.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.adv_txt_area.SetForegroundColour(wx.Colour(0, 255, 0))
        self.adv_txt_area.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyApp.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.StaticBoxSizer(self.sizer_1_staticbox, wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.single_lbl, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(self.single_txt, 0, 0, 0)
        sizer_2.Add(self.single_button, 0, wx.ALIGN_RIGHT, 0)
        sizer_1.Add(sizer_2, 0, 0, 0)
        sizer_3.Add(self.single_txt_area, 60, wx.EXPAND, 0)
        sizer_3.Add(self.single_quit_btn, 0, wx.ALIGN_RIGHT, 0)
        sizer_1.Add(sizer_3, 100, wx.EXPAND, 0)
        self.notebook_1_pane.SetSizer(sizer_1)
        sizer_7.Add(self.input_lbl, 0, 0, 0)
        sizer_7.Add(self.input_txt, 0, 0, 0)
        sizer_7.Add(self.input_btn, 0, 0, 0)
        sizer_6.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_8.Add(self.save_lbl, 0, 0, 0)
        sizer_8.Add(self.save_txt, 0, 0, 0)
        sizer_8.Add(self.save_btn, 0, 0, 0)
        sizer_6.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_9.Add(self.adv_txt, 0, 0, 0)
        sizer_9.Add(self.adv_chkbox, 0, 0, 0)
        sizer_6.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_11.Add(self.adv_txt_area, 60, wx.EXPAND, 0)
        sizer_6.Add(sizer_11, 0, wx.EXPAND, 0)
        sizer_10.Add(self.begin_btn, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 0)
        sizer_10.Add(self.adv_quit_btn, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 0)
        sizer_6.Add(sizer_10, 1, wx.ALIGN_RIGHT, 0)
        sizer_5.Add(sizer_6, 10, 0, 0)
        self.notebook_1_pane_2.SetSizer(sizer_5)
        self.notebook_1.AddPage(self.notebook_1_pane, "Single Search")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Multi Search")
        sizer_4.Add(self.notebook_1, 17, wx.EXPAND, 0)
        self.SetSizer(sizer_4)
        self.Layout()
        self.Centre()
        # end wxGlade

    def single_search(self, event): # wxGlade: MyApp.<event_handler>
        print "Event handler `single_search' not implemented"
        event.Skip()

    def close_app(self, event): # wxGlade: MyApp.<event_handler>
        wx.Window.Close(self, force=False)
        
    def about_diag(self, event): # wxGlade: MyApp.<event_handler>
        print "Event handler `about_diag' not implemented"
        event.Skip()

    def open_file(self, event): # wxGlade: MyApp.<event_handler>
        print "Event handler `open_file' not implemented"
        event.Skip()

    def save_file(self, event): # wxGlade: MyApp.<event_handler>
        print "Event handler `save_file' not implemented"
        event.Skip()

    def adv_search(self, event): # wxGlade: MyApp.<event_handler>
        print "Event handler `adv_search' not implemented"
        event.Skip()

    def perform_multi(self, event): # wxGlade: MyApp.<event_handler>
        print "Event handler `perform_multi' not implemented"
        event.Skip()

# end of class MyApp


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    mwhois_frame = MyApp(None, -1, "")
    app.SetTopWindow(mwhois_frame)
    mwhois_frame.Show()
    app.MainLoop()
